import { readDashboard } from '../services/dashboard.js';
import { escapeHTML as esc } from '../http.js';
import { renderTopbar, renderFavicon } from './pages.js';
import { assetURL, pageScript } from './assets.js';

const time = value => `<time datetime="${esc(value)}" data-dashboard-time>${esc(String(value).replace('T', ' ').replace(/\.\d+Z$/, ' UTC'))}</time>`;
const empty = message => `<p class="dashboard-empty">${message}</p>`;
const panel = (id, title, note, body) => `<details class="panel dashboard-panel" data-dashboard-panel="${id}" open><summary><span>${title}<small>${note}</small></span><span class="panel-chevron" aria-hidden="true">⌄</span></summary><div class="dashboard-panel-body">${body}</div></details>`;
const stat = (id, title, value, detail, href) => `<a href="${href}" class="dashboard-stat"><span>${title}<span aria-hidden="true">↗</span></span><strong data-stat="${id}">${value}</strong><small>${detail}</small></a>`;

export async function renderDashboardPage(env, runtime) {
	const data = await readDashboard(env, runtime);
	const states = [['active', '使用中'], ['paused', '已暂停'], ['expired', '已到期']];
	const protocols = data.protocols.length ? `<ul class="protocol-list">${data.protocols.map(item => `<li><div><strong>${esc(item.name.toUpperCase())}</strong><span>${item.count} 个 <small>· ${Math.round(item.count / data.nodeCount * 100)}%</small></span></div><div class="protocol-track" aria-hidden="true"><span style="width:${item.count / data.nodeCount * 100}%"></span></div></li>`).join('')}</ul>` : empty('还没有已保存的节点，先去主订阅添加几个吧。');
	const status = `<div class="share-total"><strong>${data.shareCount}</strong><span>个分享</span><a href="/shares">管理分享 →</a></div>${data.shareCount ? `<div class="share-status-bar" aria-hidden="true">${states.map(([key]) => `<span class="state-${key}" style="width:${data.shareCounts[key] / data.shareCount * 100}%"></span>`).join('')}</div>` : ''}<div class="share-state-counts">${states.map(([key, label]) => `<div><span><i class="state-${key}"></i>${label}</span><strong data-share-state="${key}">${data.shareCounts[key]}</strong></div>`).join('')}</div><p class="dashboard-note">暂停中的分享统一计入“已暂停”。</p>`;
	const expiry = data.expiring.length ? `<ul class="dashboard-items">${data.expiring.map(share => `<li><div><a href="/shares">${esc(share.name)}</a><small>${time(share.expiresAt)} 到期${share.paused ? ' · 已暂停' : ''}</small></div><span class="expiry-badge">待续期</span></li>`).join('')}</ul>${data.expiringCount > 8 ? '<a class="dashboard-more" href="/shares">查看全部即将到期分享 →</a>' : ''}` : empty('未来 7 天没有即将到期的分享。');
	const recent = data.recent.length ? `<ul class="dashboard-items">${data.recent.map(item => `<li><span class="change-kind">${item.kind}</span><div><a href="${item.href}">${esc(item.name)}</a><small>${time(item.at)}</small></div></li>`).join('')}</ul>` : empty('还没有修改记录，保存主订阅或创建分享后会显示在这里。');
	const html = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>个人仪表盘 · ${esc(runtime.pageTitle)}</title>${renderFavicon(runtime.browserIconURL)}<link rel="stylesheet" href="${assetURL('base.css')}"><link rel="stylesheet" href="${assetURL('dashboard.css')}"></head><body>${renderTopbar('dashboard', runtime)}<main class="dashboard"><div class="dashboard-heading"><div class="page-head"><h1>个人仪表盘</h1><p>节点、分享与最近变更，一眼掌握。</p></div><div class="dashboard-refresh"><span>更新于 ${time(data.generatedAt)}</span><a class="button" href="/dashboard">刷新概览</a></div></div>${!env.KV ? '<p class="message">绑定 KV 后即可查看已保存的节点与分享概览。</p>' : ''}<div class="dashboard-stats">${stat('nodes', '本地节点', data.nodeCount, `主订阅 ${data.mainCount}${runtime.apiSubscriptionEnabled ? ' · API ' + data.apiCount : ''} · 合并去重`, '/')}${stat('sources', '上游订阅源', data.sourceCount, '主订阅中已保存的来源链接', '/')}${stat('shares', '可用分享', data.shareCounts.active, `全部 ${data.shareCount} · 暂停 ${data.shareCounts.paused} · 到期 ${data.shareCounts.expired}`, '/shares')}${stat('expiring', '即将到期', data.expiringCount, '未来 7 天内 · 包含已暂停分享', '/shares')}</div><p class="dashboard-scope">仅统计已保存的主订阅${runtime.apiSubscriptionEnabled ? '和 API 节点' : ''}，按内容去重；不拉取上游节点，不代表测速或在线状态。</p><div class="dashboard-grid"><div class="dashboard-column">${panel('protocols', '节点协议分布', '本地节点的协议构成', protocols)}${panel('shares', '分享状态', '当前分享的可用情况', status)}${panel('expiry', '即将到期', '未来 7 天 · 最早到期优先', expiry)}</div>${panel('recent', '最近修改', '主订阅与现存分享、节点的最近变更', recent)}</div><div class="dashboard-shortcuts"><span>快捷操作</span><a href="/">编辑主订阅</a><a href="/shares">创建分享</a>${runtime.apiSubscriptionEnabled ? '<a href="/api-subscriptions">管理 API 节点</a>' : ''}<a href="/requests">查看订阅请求</a></div>${pageScript('dashboard')}</main></body></html>`;
	return new Response(html, { headers: { 'Content-Type': 'text/html;charset=utf-8', 'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff' } });
}
