export const generatedNodesStyles = `
.api-layout{display:grid;grid-template-columns:minmax(0,2fr) minmax(0,1fr);gap:18px;align-items:start}
.api-config{display:grid;gap:18px;min-width:0}.api-layout .panel{min-width:0;padding:20px}.api-layout h2{margin:0;font-size:18px}
.api-section-head{display:flex;align-items:flex-start;justify-content:space-between;flex-wrap:wrap;gap:12px;margin-bottom:16px}.api-section-head p{margin:7px 0 0;color:var(--muted);font-size:12px;line-height:1.65}
.api-title{display:flex;align-items:center;gap:9px}.count-badge,.node-kind{display:inline-block;padding:3px 7px;border:1px solid var(--line);border-radius:5px;background:var(--surface-soft);font-size:11px;color:var(--muted);white-space:nowrap}
.api-actions{display:flex;align-items:center;justify-content:flex-end;gap:8px;flex-wrap:wrap}.api-toolbar{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:14px}.api-toolbar input{min-width:0;max-width:300px}.api-toolbar .button{flex-shrink:0}
.api-template-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(min(100%,240px),1fr));gap:8px;max-height:480px;overflow:auto;align-content:start}
.api-template-card{border:1px solid var(--line-soft);border-radius:6px;padding:12px;min-width:0}.api-template-heading{display:flex;align-items:center;gap:8px}.api-template-heading strong{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px}
.api-template-card small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font:11px/1.7 ui-monospace,monospace;color:var(--muted);margin-top:5px}.api-template-card .api-actions{margin-top:10px}.api-template-card .button{min-height:28px;padding:4px 9px;font-size:11px}.api-template-card .message{font-size:12px;margin:6px 0}
.api-port-field{display:flex;align-items:center;gap:8px;margin-top:10px;font-size:12px}.api-port-field input{min-width:0;flex:1;width:100px;padding:7px 8px;border:1px solid var(--line);border-radius:6px;background:#fff;color:var(--text);font-family:inherit;font-size:12px}.api-port-field label{flex:none;margin:0;font-size:12px}
.empty-list{grid-column:1/-1;padding:28px 14px;border:1px dashed var(--line);border-radius:8px;color:var(--muted);font-size:13px;text-align:center}.api-save-state{margin:12px 0 0;font-size:12px}.api-save-state:empty{display:none}
.credential-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.token-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px}.token-actions{display:flex;gap:7px}.token-actions .button{padding:0 10px}.token-row input{font:12px ui-monospace,monospace;min-width:0}
.quick-api{margin-top:6px;padding-top:16px;border-top:1px solid var(--line-soft)}.quick-api-head{margin-bottom:12px}.quick-api-head strong{display:block;font-size:14px}.quick-api-head small{display:block;margin-top:6px;color:var(--muted);line-height:1.65}.quick-api-grid{display:grid;gap:8px}.api-call-row{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:8px;padding:8px;border:1px solid var(--line);border-radius:7px;background:#f8faf8}.api-call-row code{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:10px;color:var(--muted)}.api-call-row .button{padding:5px 9px;font-size:11px;min-height:30px}.method-badge{padding:3px 5px;border-radius:4px;background:var(--green);color:#fff;font-size:10px;font-weight:800}
.node-list{display:grid;gap:9px;max-height:75vh;overflow:auto;align-content:start}.node-card{min-width:0;padding:12px;border:1px solid var(--line);border-radius:8px}.node-head{display:flex;gap:7px;align-items:center}.node-head strong{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px}.node-meta,.node-content{margin-top:6px;color:var(--muted);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:10px}.node-content{font-family:ui-monospace,monospace}.node-actions{display:flex;justify-content:flex-end;gap:7px;margin-top:10px}.node-actions .button{padding:5px 9px;font-size:11px;min-height:30px}.danger-button{border-color:#f2c6c2;color:var(--danger)}
.api-dialog{width:min(740px,calc(100% - 32px));padding:0;border:1px solid var(--line);border-radius:10px;background:#fff;box-shadow:0 24px 80px rgba(20,45,33,.2);max-height:90vh;overflow:auto}.api-dialog::backdrop{background:rgba(16,32,24,.38)}.api-dialog-head{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:16px 18px;border-bottom:1px solid var(--line)}.api-dialog-head h3{margin:0;font-size:17px}.dialog-close{width:30px;height:30px;border:0;background:transparent;font-size:22px;color:var(--muted);cursor:pointer}.api-dialog-body{padding:18px}.api-dialog-actions{display:flex;align-items:center;justify-content:flex-end;gap:8px;padding:14px 18px;border-top:1px solid var(--line);flex-wrap:wrap}.api-dialog-actions>span{margin-right:auto;font-size:12px}
.template-tools{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:12px}.template-tools input{flex:1;min-width:140px}.template-tools .button{min-height:36px;padding:0 10px;font-size:12px}.template-original-list{display:grid;gap:8px;max-height:45vh;overflow:auto;align-content:start}.template-choice{border:1px solid var(--line);border-radius:7px;padding:10px}.template-choice:has(input:checked){border-color:var(--green);background:var(--green-soft)}.template-original{display:flex;align-items:flex-start;gap:9px;margin:0;cursor:pointer}.template-original input{margin:3px 0;flex:none}.template-original>span{min-width:0}.template-original strong{display:block;font-size:12px;overflow-wrap:anywhere}.template-original small{display:block;font-size:11px;overflow-wrap:anywhere;color:var(--muted);margin-top:3px}.template-choice.unavailable{opacity:.65}.template-choice .api-port-field{margin-left:23px;max-width:300px}.api-dialog [hidden]{display:none!important}
.api-preview-code{width:100%;min-height:150px;resize:vertical;font:12px/1.65 ui-monospace,monospace}.api-preview-name{overflow-wrap:anywhere;font-size:13px}
.confirm-dialog{width:min(420px,calc(100% - 32px))}.confirm-body{padding:24px}.confirm-body h3{margin:0 0 8px}.confirm-body p{margin:0;color:var(--muted);line-height:1.65}.confirm-actions{display:flex;justify-content:flex-end;gap:9px;padding:0 24px 20px}
@media(max-width:980px){.api-layout{grid-template-columns:1fr}.node-list{max-height:480px}}@media(max-width:700px){.credential-grid{grid-template-columns:1fr}.api-layout .panel{padding:14px}.api-template-grid{max-height:360px}.template-tools input{flex-basis:100%}.api-toolbar{flex-wrap:wrap}.api-toolbar input{max-width:none;flex:1 1 160px}}@media(max-width:420px){.token-row{grid-template-columns:1fr}.token-actions{justify-content:flex-start}}
`;

export const generatedNodesMarkup = `
<div class="page-head"><h1>API 订阅</h1><p>从原始节点添加模板，通过 API 传入地址生成节点，并自动附加到主订阅结果末尾。</p></div>
<div class="api-layout">
<form id="settingsForm" class="api-config">
 <section class="panel" id="apiTemplateSection">
  <div class="api-section-head"><div><div class="api-title"><h2>节点模板</h2><span class="count-badge" id="templateCount">0 / 20</span></div><p>关联原始节点；原始节点修改后，后续 API 调用自动使用最新内容。</p></div><button class="button primary" id="saveSettings" type="submit">保存配置</button></div>
  <div class="api-toolbar"><input id="savedTemplateSearch" type="search" placeholder="搜索已有模板" aria-label="搜索已有模板"><button class="button" id="addTemplate" type="button">＋ 添加模板</button></div>
  <div id="templateList" class="api-template-grid"></div>
  <p class="muted api-save-state">端口优先级：模板指定端口 &gt; API 传入端口 &gt; 默认 8443。</p>
  <p id="settingsMessage" class="api-save-state muted" role="status"></p>
 </section>
 <section class="panel"><div class="api-section-head"><h2>API 配置</h2></div>
  <div class="credential-grid"><div class="field"><label for="apiToken">唯一 API Token</label><div class="token-row"><input id="apiToken" type="text" maxlength="128" readonly><div class="token-actions"><button class="button" id="copyToken" type="button">复制</button><button class="button" id="resetToken" type="button">重置</button></div></div><small>首次打开时自动生成；重置并保存后，旧 Token 和旧调用 URL 立即失效。</small></div>
  <div class="field"><label for="nameTemplate">节点名称格式</label><input id="nameTemplate" type="text" maxlength="160" required placeholder="{{name}}-{{address}}:{{port}}"><small><code>{{name}}</code> 为原始节点名称，<code>{{address}}</code> 为 API 地址，<code>{{port}}</code> 为最终端口；支持 <code>{{type}}</code>、slice 和 split。</small></div></div>
  <div class="quick-api"><div class="quick-api-head"><strong>API 调用</strong><small>GET 的 address 必填，port 可选；省略端口时使用模板端口或 8443。POST 可直接上传完整节点。</small></div><div class="quick-api-grid"><div class="api-call-row"><span class="method-badge">GET</span><code id="addressExample" title="地址必填，端口可选"></code><button class="button" type="button" data-copy-example="addressExample">复制 URL</button></div><div class="api-call-row"><span class="method-badge">POST</span><code id="directExample" title="完整节点 curl 命令"></code><button class="button" type="button" data-copy-example="directExample">复制命令</button></div></div></div>
 </section>
</form>
<section class="panel nodes-panel"><div class="api-section-head"><div><h2>API 生成节点</h2><p>按追加顺序展示，自动附加到主订阅末尾。</p></div><span class="count-badge" id="nodeCount">0 个</span></div><div id="nodeList" class="node-list"></div></section>
</div>
<dialog id="templatePickerDialog" class="api-dialog" aria-labelledby="templatePickerTitle"><form id="templatePickerForm"><div class="api-dialog-head"><h3 id="templatePickerTitle">从原始节点添加模板</h3><button id="closeTemplatePicker" class="dialog-close" type="button" aria-label="关闭">×</button></div><div class="api-dialog-body"><div class="template-tools"><input id="templateSearch" type="search" placeholder="搜索节点名称、协议或地址" aria-label="搜索原始节点"><button id="selectTemplateResults" type="button" class="button">选择当前结果</button></div><p class="muted">选择后可指定模板端口；留空时使用 API 传入端口，未传入则使用 8443。</p><div id="templateOriginalList" class="template-original-list"></div><p id="templateSelectionMessage" class="muted" role="status"></p><button id="retryTemplateOriginals" class="button" type="button" hidden>重新加载</button></div><div class="api-dialog-actions"><span id="pendingTemplateCount">已选择 0 个</span><button id="cancelTemplatePicker" class="button" type="button">取消</button><button id="confirmAddTemplates" class="button primary" type="submit" disabled>添加模板</button></div></form></dialog>
<dialog id="templatePreviewDialog" class="api-dialog" aria-labelledby="templatePreviewTitle"><div class="api-dialog-head"><h3 id="templatePreviewTitle">生成预览</h3><button id="closeTemplatePreview" class="dialog-close" type="button" aria-label="关闭">×</button></div><div class="api-dialog-body"><p class="muted">以 edge.example.com 为例，API 未传入端口。</p><p id="templatePreviewName" class="api-preview-name"></p><textarea id="templatePreview" class="api-preview-code" readonly aria-label="生成节点预览"></textarea></div></dialog>
<dialog id="confirmDialog" class="api-dialog confirm-dialog" aria-labelledby="confirmTitle"><div class="confirm-body"><h3 id="confirmTitle">请确认操作</h3><p id="confirmText"></p></div><div class="confirm-actions"><button class="button" id="confirmCancel" type="button">取消</button><button class="button primary" id="confirmAccept" type="button">确认</button></div></dialog>
`;