import { subscriptionCardStyles } from './subscription-cards.js';

export const generatedNodesStyles = `
.api-layout{display:grid;grid-template-columns:minmax(520px,1.35fr) minmax(320px,1fr);gap:18px;align-items:start}
.api-config{display:grid;gap:18px;min-width:0}.api-layout .panel{min-width:0;padding:20px}.api-layout h2{margin:0;font-size:18px}
.api-section-head{display:flex;align-items:flex-start;justify-content:space-between;flex-wrap:wrap;gap:12px;margin-bottom:16px}.api-section-head p{margin:7px 0 0;color:var(--muted);font-size:12px;line-height:1.65}
.api-title{display:flex;align-items:center;gap:9px}.count-badge,.node-kind{display:inline-block;padding:3px 7px;border:1px solid var(--line);border-radius:5px;background:var(--surface-soft);font-size:11px;color:var(--muted);white-space:nowrap}
.api-actions{display:flex;align-items:center;justify-content:flex-end;gap:8px;flex-wrap:wrap}.api-toolbar{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:14px}.api-toolbar input{min-width:0;max-width:300px}.api-toolbar .button{flex-shrink:0}
.api-template-grid{max-height:480px;overflow:auto}
.api-wizard-steps{display:flex;gap:18px;margin:0 0 18px;padding:0;list-style:none;color:var(--muted);font-size:13px}.api-wizard-steps [aria-current="step"]{color:var(--green);font-weight:700}.api-wizard-step{border:0;padding:0;margin:0;min-width:0}.api-port-control{display:grid;gap:7px;min-width:0}.api-port-control select,.api-port-control input{width:100%;min-width:0;padding:9px 10px;border:1px solid var(--line);border-radius:6px;background:#fff;color:var(--text);font:inherit;font-size:13px}.api-port-control label{margin:0;font-size:12px}.api-port-bulk{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:start;gap:10px;padding:12px;margin-bottom:14px;background:var(--green-soft);border-radius:7px}.api-port-bulk .api-port-control label{display:none}.api-port-bulk>label{margin:10px 0;font-size:12px}.api-port-bulk .button{min-height:37px;padding:0 10px;font-size:12px}.api-port-review{display:grid;gap:8px;max-height:40vh;overflow:auto;align-content:start}.api-port-review-row{display:grid;grid-template-columns:minmax(0,1fr) 190px;align-items:start;gap:16px;border:1px solid var(--line);border-radius:7px;padding:12px}.api-port-review-row strong{display:block;font-size:13px;overflow-wrap:anywhere}.api-port-review-row small{display:block;margin-top:5px;color:var(--muted);font-size:11px;overflow-wrap:anywhere}.api-port-review-row .api-port-control label{display:none}.api-port-review-row .api-port-control input{font-family:inherit}.api-wizard-help{margin:0 0 14px;font-size:13px;color:var(--muted);line-height:1.65}
@media(max-width:550px){#templatePickerDialog .api-dialog-actions>span{flex-basis:100%;margin:0 0 4px}#templatePickerDialog .api-dialog-actions>.button{flex:1;min-height:40px;padding:0 8px;font-size:12px}.api-port-bulk{grid-template-columns:minmax(0,1fr) auto}.api-port-bulk>label{grid-column:1/-1;margin:0}.api-port-review-row{grid-template-columns:minmax(0,1fr);gap:10px}}
.empty-list{grid-column:1/-1;padding:28px 14px;border:1px dashed var(--line);border-radius:8px;color:var(--muted);font-size:13px;text-align:center}.api-save-state{margin:12px 0 0;font-size:12px}.api-save-state:empty{display:none}
.credential-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;align-items:start}.credential-grid .field{min-width:0;align-content:start}.credential-grid input[type=text],.token-actions .button{height:44px}.token-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px}.token-actions{display:flex;gap:7px}.token-actions .button{padding:0 10px}.token-row input{font:12px ui-monospace,monospace;min-width:0}
.quick-api{margin-top:6px;padding-top:16px;border-top:1px solid var(--line-soft)}.quick-api-head{margin-bottom:12px}.quick-api-head strong{display:block;font-size:14px}.quick-api-head small{display:block;margin-top:6px;color:var(--muted);line-height:1.65}.quick-api-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.api-call-row{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:8px;padding:8px;border:1px solid var(--line);border-radius:7px;background:#f8faf8}.api-call-row code{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:10px;color:var(--muted)}.api-call-row .button{padding:5px 9px;font-size:11px;min-height:30px}.method-badge{padding:3px 5px;border-radius:4px;background:var(--green);color:#fff;font-size:10px;font-weight:800}
.node-list{max-height:75vh;overflow:auto}.danger-button{border-color:#f2c6c2;color:var(--danger)}
.api-dialog{width:min(740px,calc(100% - 32px));padding:0;border:1px solid var(--line);border-radius:10px;background:#fff;box-shadow:0 24px 80px rgba(20,45,33,.2);max-height:90vh;overflow:auto}.api-dialog::backdrop{background:rgba(16,32,24,.38)}.api-dialog-head{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:16px 18px;border-bottom:1px solid var(--line)}.api-dialog-head h3{margin:0;font-size:17px}.dialog-close{width:30px;height:30px;border:0;background:transparent;font-size:22px;color:var(--muted);cursor:pointer}.api-dialog-body{padding:18px}.api-dialog-actions{display:flex;align-items:center;justify-content:flex-end;gap:8px;padding:14px 18px;border-top:1px solid var(--line);flex-wrap:wrap}.api-dialog-actions>span{margin-right:auto;font-size:12px}
.template-tools{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:12px}.template-tools input{flex:1;min-width:140px}.template-tools .button{min-height:36px;padding:0 10px;font-size:12px}.template-original-list{display:grid;gap:8px;max-height:45vh;overflow:auto;align-content:start}.template-choice{border:1px solid var(--line);border-radius:7px;padding:10px}.template-choice:has(input:checked){border-color:var(--green);background:var(--green-soft)}.template-original{display:flex;align-items:flex-start;gap:9px;margin:0;cursor:pointer}.template-original input{margin:3px 0;flex:none}.template-original>span{min-width:0}.template-original strong{display:block;font-size:12px;overflow-wrap:anywhere}.template-original small{display:block;font-size:11px;overflow-wrap:anywhere;color:var(--muted);margin-top:3px}.template-choice.unavailable{opacity:.65}.api-dialog [hidden]{display:none!important}
.api-preview-code{width:100%;min-height:150px;resize:vertical;font:12px/1.65 ui-monospace,monospace}.api-preview-name{overflow-wrap:anywhere;font-size:13px}
.confirm-dialog{width:min(420px,calc(100% - 32px))}.confirm-body{padding:24px}.confirm-body h3{margin:0 0 8px}.confirm-body p{margin:0;color:var(--muted);line-height:1.65}.confirm-actions{display:flex;justify-content:flex-end;gap:9px;padding:0 24px 20px}
@media(max-width:960px){.api-layout{grid-template-columns:1fr}.node-list{max-height:480px}}@media(max-width:700px){.credential-grid{grid-template-columns:1fr}.api-layout .panel{padding:14px}.api-template-grid{max-height:360px}.template-tools input{flex-basis:100%}.api-toolbar{flex-wrap:wrap}.api-toolbar input{max-width:none;flex:1 1 160px}}@media(max-width:420px){.token-row{grid-template-columns:1fr}.token-actions{justify-content:flex-start}}
@media(max-width:550px){.api-call-row{grid-template-columns:auto minmax(0,1fr)}.api-call-row .button{grid-column:1/-1;justify-self:end}}
${subscriptionCardStyles}
`;

export const generatedNodesMarkup = `
<div class="page-head"><h1>API 订阅</h1><p>从原始节点添加模板，通过 API 传入地址生成节点，并自动附加到主订阅结果末尾。</p></div>
<div class="api-layout">
<div class="api-config"><form id="settingsForm">
 <section class="panel" id="apiTemplateSection">
  <div class="api-section-head"><div><div class="api-title"><h2>节点模板</h2><span class="count-badge" id="templateCount">0 / 20</span></div><p>关联原始节点；原始节点修改后，后续 API 调用自动使用最新内容。</p></div><button class="button primary" id="saveSettings" type="submit">保存模板</button></div>
  <div class="api-toolbar"><input id="savedTemplateSearch" type="search" placeholder="搜索已有模板" aria-label="搜索已有模板"><button class="button" id="addTemplate" type="button">＋ 添加模板</button></div>
  <div id="templateList" class="api-template-grid subscription-card-grid"></div>
  <p class="muted api-save-state">端口优先级：模板指定端口 &gt; API 传入端口 &gt; 默认 8443。</p>
  <p id="settingsMessage" class="api-save-state muted" role="status"></p>
 </section></form>
 <form id="apiSettingsForm" class="panel"><div class="api-section-head"><h2>API 配置</h2><button class="button primary" id="saveAPISettings" type="submit">保存 API 配置</button></div>
  <div class="credential-grid"><div class="field"><label for="apiToken">唯一 API Token</label><div class="token-row"><input id="apiToken" type="text" maxlength="128" readonly><div class="token-actions"><button class="button" id="copyToken" type="button">复制</button><button class="button" id="resetToken" type="button">重置</button></div></div><small>首次打开时自动生成；重置并保存后，旧 Token 和旧调用 URL 立即失效。</small></div>
  <div class="field"><label for="nameTemplate">节点名称格式</label><input id="nameTemplate" type="text" maxlength="160" required placeholder="{{name}}-{{address}}:{{port}}"><small><code>{{name}}</code> 为原始节点名称，<code>{{address}}</code> 为 API 地址，<code>{{port}}</code> 为最终端口；支持 <code>{{type}}</code>、slice 和 split。</small></div></div>
  <div class="quick-api"><div class="quick-api-head"><strong>API 调用</strong><small>GET 的 address 必填，port 可选；省略端口时使用模板端口或 8443。POST 可直接上传完整节点。</small></div><div class="quick-api-grid"><div class="api-call-row"><span class="method-badge">GET</span><code id="addressExample" title="地址必填，端口可选"></code><button class="button" type="button" data-copy-example="addressExample">复制 URL</button></div><div class="api-call-row"><span class="method-badge">POST</span><code id="directExample" title="完整节点 curl 命令"></code><button class="button" type="button" data-copy-example="directExample">复制命令</button></div></div></div>
 <p id="apiSettingsMessage" class="api-save-state muted" role="status"></p>
 </form>
</div>
<section class="panel nodes-panel"><div class="api-section-head"><div><h2>API 生成节点</h2><p>按追加顺序展示，自动附加到主订阅末尾。</p></div><span class="count-badge" id="nodeCount">0 个</span></div><div id="nodeList" class="node-list subscription-card-grid"></div></section>
</div>
<dialog id="templatePickerDialog" class="api-dialog" aria-labelledby="templatePickerTitle"><form id="templatePickerForm" novalidate><div class="api-dialog-head"><h3 id="templatePickerTitle">添加节点模板</h3><button id="closeTemplatePicker" class="dialog-close" type="button" aria-label="关闭">×</button></div><div class="api-dialog-body">
<ol class="api-wizard-steps" id="templateWizardSteps" aria-label="添加步骤"><li id="templateSelectStepLabel" aria-current="step">1 · 选择原始节点</li><li id="templatePortStepLabel">2 · 设置端口</li></ol>
<fieldset id="templateSelectStep" class="api-wizard-step"><div class="template-tools"><input id="templateSearch" type="search" placeholder="搜索节点名称、协议或地址" aria-label="搜索原始节点"><button id="selectTemplateResults" type="button" class="button">选择当前结果</button></div><p class="api-wizard-help">选择要添加的原始节点，已添加的节点不可重复选择。</p><div id="templateOriginalList" class="template-original-list"></div></fieldset>
<fieldset id="templatePortStep" class="api-wizard-step" hidden disabled><p class="api-wizard-help">默认跟随 API；API 未传入端口时使用 8443。也可统一指定端口，或分别调整。</p><div class="api-port-bulk" id="templateBulkPort"><label>统一端口</label><div id="bulkTemplatePort"></div><button type="button" class="button" id="applyBulkTemplatePort">应用到全部</button></div><div id="templatePortReview" class="api-port-review"></div></fieldset>
<p id="templateSelectionMessage" class="muted" role="status"></p><button id="retryTemplateOriginals" class="button" type="button" hidden>重新加载</button></div><div class="api-dialog-actions"><span id="pendingTemplateCount">已选择 0 个</span><button id="cancelTemplatePicker" class="button" type="button">取消</button><button id="previousTemplateStep" class="button" type="button" hidden>上一步</button><button id="nextTemplateStep" class="button primary" type="button" disabled>下一步</button><button id="confirmAddTemplates" class="button primary" type="submit" hidden>添加模板</button></div></form></dialog>
<dialog id="templatePreviewDialog" class="api-dialog" aria-labelledby="templatePreviewTitle"><div class="api-dialog-head"><h3 id="templatePreviewTitle">生成预览</h3><button id="closeTemplatePreview" class="dialog-close" type="button" aria-label="关闭">×</button></div><div class="api-dialog-body"><p class="muted">以 edge.example.com 为例，API 未传入端口。</p><p id="templatePreviewName" class="api-preview-name"></p><textarea id="templatePreview" class="api-preview-code" readonly aria-label="生成节点预览"></textarea></div></dialog>
<dialog id="confirmDialog" class="api-dialog confirm-dialog" aria-labelledby="confirmTitle"><div class="confirm-body"><h3 id="confirmTitle">请确认操作</h3><p id="confirmText"></p></div><div class="confirm-actions"><button class="button" id="confirmCancel" type="button">取消</button><button class="button primary" id="confirmAccept" type="button">确认</button></div></dialog>
`;