const pageData = JSON.parse(document.getElementById('page-data-generated-nodes').textContent);
var settings=pageData.settings;
		var nodes=pageData.nodes;
		var form=document.getElementById('settingsForm');
		var tokenInput=document.getElementById('apiToken');
		var nameInput=document.getElementById('nameTemplate');
		var templateInput=document.getElementById('nodeTemplate');
		var list=document.getElementById('nodeList');
		function esc(value){return String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
		function copyText(value){return navigator.clipboard.writeText(value)}
		function askConfirm(message,title){return new Promise(function(resolve){var dialog=document.getElementById('confirmDialog');document.getElementById('confirmTitle').textContent=title||'请确认操作';document.getElementById('confirmText').textContent=message;function finish(value){dialog.close();dialog.oncancel=null;document.getElementById('confirmAccept').removeEventListener('click',accept);document.getElementById('confirmCancel').removeEventListener('click',cancel);resolve(value)}function accept(){finish(true)}function cancel(){finish(false)}document.getElementById('confirmAccept').addEventListener('click',accept);document.getElementById('confirmCancel').addEventListener('click',cancel);dialog.oncancel=function(event){event.preventDefault();cancel()};dialog.showModal()})}
		function randomToken(){var bytes=new Uint8Array(24);crypto.getRandomValues(bytes);var binary='';bytes.forEach(function(value){binary+=String.fromCharCode(value)});return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
		function syncExamples(){var endpoint=window.location.origin+'/api/import';var token='?token='+encodeURIComponent(tokenInput.value);document.getElementById('addressExample').textContent=endpoint+token+'&address={{address1}}&port={{port1}}&address={{address2}}&port={{port2}}';document.getElementById('directExample').textContent='curl -X POST "'+endpoint+'" -H "X-API-Token: '+tokenInput.value+'" -H "Content-Type: text/plain;charset=UTF-8" --data-binary "{{node1}}\n{{node2}}"'}
		function render(){document.getElementById('nodeCount').textContent=nodes.length+' 个';if(!nodes.length){list.innerHTML='<div class="empty-list">尚无节点。请通过 GET 地址接口或 POST 完整节点接口从外部追加。</div>';return}list.innerHTML=nodes.map(function(node){var meta=node.address?(esc(node.address)+(node.port?':'+node.port:'')):'完整节点';return '<article class="node-card"><div class="node-main"><div class="node-head"><span class="node-kind">'+(node.kind==='raw'?'完整节点':'模板生成')+'</span><strong title="'+esc(node.name)+'">'+esc(node.name)+'</strong></div><div class="node-meta">'+meta+' · '+new Date(node.createdAt).toLocaleString()+'</div><div class="node-content" title="'+esc(node.content)+'">'+esc(node.content)+'</div></div><div class="node-actions"><button class="button" type="button" data-copy-node="'+node.id+'">复制</button><button class="button danger-button" type="button" data-delete="'+node.id+'">删除</button></div></article>'}).join('')}
		function apiCall(method,body){return fetch('/api/generated-nodes',{method:method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}).then(function(response){return response.json().then(function(data){if(!response.ok)throw new Error(data.message||'操作失败');return data})})}
		tokenInput.value=settings.token;nameInput.value=settings.nameTemplate;templateInput.value=settings.nodeTemplate;syncExamples();render();
		document.getElementById('regenerateToken').addEventListener('click',function(){askConfirm('保存新 Token 后，旧 Token 和旧调用 URL 会立即失效。','重新生成 API Token').then(function(accepted){if(!accepted)return;tokenInput.value=randomToken();syncExamples();document.getElementById('settingsMessage').textContent='新 Token 尚未保存'})});
		document.querySelectorAll('[data-copy-example]').forEach(function(button){button.addEventListener('click',function(){copyText(document.getElementById(button.dataset.copyExample).textContent).then(function(){var original=button.textContent;button.textContent='已复制';setTimeout(function(){button.textContent=original},1200)})})});
		form.addEventListener('submit',function(event){event.preventDefault();var button=document.getElementById('saveSettings');var message=document.getElementById('settingsMessage');button.disabled=true;message.textContent='正在保存…';apiCall('PUT',{token:tokenInput.value,nameTemplate:nameInput.value,nodeTemplate:templateInput.value}).then(function(data){settings=data.settings;tokenInput.value=settings.token;nameInput.value=settings.nameTemplate;templateInput.value=settings.nodeTemplate;syncExamples();message.textContent='模板与唯一 Token 已保存';message.className='success'}).catch(function(error){message.textContent=error.message;message.className='message'}).finally(function(){button.disabled=false})});
		list.addEventListener('click',function(event){var copyButton=event.target.closest('[data-copy-node]');if(copyButton){var node=nodes.find(function(item){return item.id===copyButton.dataset.copyNode});if(node)copyText(node.content).then(function(){var original=copyButton.textContent;copyButton.textContent='已复制';setTimeout(function(){copyButton.textContent=original},1200)});return}var button=event.target.closest('[data-delete]');if(!button)return;askConfirm('删除后，该节点也会从主订阅的动态附加结果中消失。','删除 API 节点').then(function(accepted){if(!accepted)return;button.disabled=true;apiCall('DELETE',{id:button.dataset.delete}).then(function(){nodes=nodes.filter(function(node){return node.id!==button.dataset.delete});render()}).catch(function(error){button.disabled=false;document.getElementById('settingsMessage').textContent=error.message;document.getElementById('settingsMessage').className='message'})})});
